console_title_template = ' {{ .Folder }} :: {{if .Root}}Admin{{end}}'
version = 3
enable_cursor_positioning = true
final_space = true

[palette]
  blue-bell = '#9aa5ce'
  blue-black = '#565f89'
  celeste-blue = '#b4f9f8'
  light-sky-blue = '#7dcfff'
  main-bg = '#24283b'
  pastal-grey = '#cfc9c2'
  pistachio-green = '#9ece6a'
  t-background = 'p:main-bg'
  terminal-black = '#414868'
  terminal-blue = '#7aa2f7'
  terminal-green = '#73daca'
  terminal-magenta = '#bb9af7'
  terminal-red = '#f7768e'
  terminal-white = '#c0caf5'
  terminal-yellow = '#e0af68'
  white-blue = '#a9b1d6'

[secondary_prompt]
  template = '❯❯ '
  foreground = 'p:light-sky-blue'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  foreground = ''
  background = 'transparent'
  foreground_templates = ['{{ if gt .Code 0 }}p:terminal-red{{ end }}', '{{ if eq .Code 0 }}p:light-sky-blue{{ end }}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'plain'
    template = '{{ .Path }}'
    foreground = 'p:terminal-magenta'
    background = 'transparent'
    type = 'path'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    style = 'plain'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} {{ if gt .Behind 0 }}<cyan></cyan>{{ end }}{{ if gt .Ahead 0 }}<cyan></cyan>{{ end }}'
    foreground = 'p:pastal-grey'
    background = 'transparent'
    type = 'git'

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    style = 'plain'
    template = '{{ .FormattedMs }} '
    foreground = 'p:terminal-yellow'
    background = 'transparent'
    type = 'executiontime'

    [blocks.segments.properties]
      threshold = 5000

  [[blocks.segments]]
    style = 'plain'
    template = ' {{ .Full }} '
    foreground = 'p:pistachio-green'
    background = ''
    type = 'node'

  [[blocks.segments]]
    style = 'plain'
    template = ' {{ .Full }} '
    foreground = 'p:terminal-blue'
    background = ''
    type = 'php'

  [[blocks.segments]]
    style = 'plain'
    template = ' {{ .Full }} '
    foreground = 'p:terminal-yellow'
    background = ''
    type = 'python'

  [[blocks.segments]]
    style = 'plain'
    template = ' {{ .Full }} '
    foreground = 'p:terminal-magenta'
    background = ''
    type = 'julia'

  [[blocks.segments]]
    style = 'plain'
    template = ' {{ .Full}} '
    foreground = 'p:terminal-red'
    background = ''
    type = 'ruby'

  [[blocks.segments]]
    style = 'plain'
    template = 'ﳑ {{ .Full}} '
    foreground = 'p:light-sky-blue'
    background = ''
    type = 'go'

  [[blocks.segments]]
    style = 'plain'
    foreground = 'p:white-blue'
    background = ''
    type = 'command'

    [blocks.segments.properties]
      command = 'git log --pretty=format:%cr -1 || date +%H:%M:%S'
      shell = 'zsh'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'plain'
    template = '❯'
    foreground = ''
    background = ''
    type = 'text'
    foreground_templates = ['{{ if gt .Code 0 }}p:terminal-red{{ end }}', '{{ if eq .Code 0 }}p:light-sky-blue{{ end }}']
