version = 2
final_space = true
console_title_template = ' {{ .Folder }} :: {{if .Root}}Admin{{end}}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
  type = 'path'
  style = 'plain'
  background = 'transparent'
  foreground = 'p:terminal-magenta'
  template = "{{.Path }}"

  [blocks.segments.properties]
  style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'p:pastal-grey'
    background = 'transparent'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} {{ if gt .Behind 0 }}<cyan></cyan>{{ end }}{{ if gt .Behind 0 }}<cyan></cyan>{{ end }}'

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'p:terminal-yellow'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 5000


  [[blocks.segments]]
    type = 'node'
    style = 'plain'
    foreground = 'p:pistachio-green'
    template = ' {{ .Full }} '

  [[blocks.segments]]
    type = 'php'
    style = 'plain'
    foreground = 'p:terminal-blue'
    template = ' {{ .Full }} '

  [[blocks.segments]]
    type = 'python'
    style = 'plain'
    foreground = 'p:terminal-yellow'
    template = ' {{ .Full }}'

  [[blocks.segments]]
    type = 'julia'
    style = 'plain'
    foreground = 'p:terminal-magenta'
    template = ' {{ .Full }}'

  [[blocks.segments]]
    type = 'ruby'
    style = 'plain'
    foreground = 'p:terminal-red'
    template = ' {{ .Full}}'

  [[blocks.segments]]
    type = 'go'
    style = 'plain'
    foreground = 'p:light-sky-blue'
    template = 'ﳑ {{ .Full}}'

  [[blocks.segments]]
    type = 'command'
    style = 'plain'
    foreground = 'p:white-blue'

    [blocks.segments.properties]
      command = 'git log --pretty=format:%cr -1 || date +%H:%M:%S'
      shell = 'zsh'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true
  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{ if gt .Code 0 }}p:terminal-red{{ end }}",
      "{{ if eq .Code 0 }}p:light-sky-blue{{ end }}",
    ]
    template = ''

[transient_prompt]
    foreground_templates = [
      "{{ if gt .Code 0 }}p:terminal-red{{ end }}",
      "{{ if eq .Code 0 }}p:light-sky-blue{{ end }}",
    ]
  background = 'transparent'
  template = ' '

[secondary_prompt]
  foreground = 'p:light-sky-blue'
  background = 'transparent'
  template = ' '

[palette]
  blue-bell = '#9aa5ce'
  blue-black = '#565f89'
  celeste-blue = '#b4f9f8'
  light-sky-blue = '#7dcfff'
  main-bg = '#24283b'
  pastal-grey = '#cfc9c2'
  pistachio-green = '#9ece6a'
  t-background = 'p:main-bg'
  terminal-black = '#414868'
  terminal-blue = '#7aa2f7'
  terminal-green = '#73daca'
  terminal-magenta = '#bb9af7'
  terminal-red = '#f7768e'
  terminal-white = '#c0caf5'
  terminal-yellow = '#e0af68'
  white-blue = '#a9b1d6'
